### ISSUE TITLE
Links back to github repos are missing

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/libraries#2]
The libraries don't have links back to github. Each one should link back to the relevant repo.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Usually, we add it to the lib readmes as badges so cross-links available on github/pypi/docs/etc:

![github](https://user-images.githubusercontent.com/557395/128623673-cb311216-64a0-44e4-ba0d-bb589a1bdd46.png)

But I need to ensure that all the libs have them and sync with the latest form I use for frictionless-py

**Comment by roll** [comment]
All the tableschema/datapackage now have `codebase: github` badges - https://libraries.frictionlessdata.io/docs/data-package/python
